# Generated by Django 4.2.7 on 2023-11-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timer', '0002_remove_timer_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='elapsed_time',
            field=models.IntegerField(default=0),
        ),
    ]
